In [2]:
# Array Introduction
# Building numpy array
import numpy as np

In [3]:
# Creat from python list
list_1 = [1,2,3,4]

In [4]:
list_1

[1, 2, 3, 4]

In [5]:
array_1 = np.array(list_1)
array_1

array([1, 2, 3, 4])

In [6]:
list_2 = [5,6,7,8]
array_2 = np.array([list_1, list_2])
array_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
print(array_2.dtype)
print(array_2.shape)
print(array_2.size)

int64
(2, 4)
8


In [17]:
array_3 = np.array([[1.0,2,3], [4.0,5,6]])
array_3.dtype

dtype('float64')

In [21]:
array_4 = np.arange(1, 10, 2)
array_4

array([1, 3, 5, 7, 9])

In [23]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [24]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
print(np.eye(5))
print(np.eye(5).dtype)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
float64


In [29]:
a = np.arange(1,10)
print(a[1])
print(a[1:5])

2
[2 3 4 5]


In [33]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)
print(c[:2, 1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]
