In [1]:
# using pickle for serialization
import pickle
import numpy as np

In [17]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
f = open("x.pkl", "wb")

In [19]:
pickle.dump(x, f)
!ls

Applications                   PycharmProjects
Desktop                        Sites
Documents                      TeamViewer
Downloads                      Untitled.ipynb
Dropbox                        Untitled1.ipynb
Google Drive                   VirtualBox VMs
IdeaProjects                   anaconda3
Library                        mcuxpresso
Movies                         my_first_django_project
Music                          temp.pkl
NumpyArrayInputAndOutput.ipynb untitled
Pictures                       untitled1
Public                         x.pkl


In [20]:
f = open("x.pkl", "rb")
pickle.load(f)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# serialize by Numpy
np.save("one_array", x)
!ls

Applications                   Sites
Desktop                        TeamViewer
Documents                      Untitled.ipynb
Downloads                      Untitled1.ipynb
Dropbox                        VirtualBox VMs
Google Drive                   anaconda3
IdeaProjects                   mcuxpresso
Library                        my_first_django_project
Movies                         one_array.npy
Music                          temp.pkl
NumpyArrayInputAndOutput.ipynb untitled
Pictures                       untitled1
Public                         x.pkl
PycharmProjects


In [24]:
np.load("one_array.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
y = np.arange(20)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [29]:
np.savez("two_array.npz", a = x, b = y)
!ls

Applications                   Sites
Desktop                        TeamViewer
Documents                      Untitled.ipynb
Downloads                      Untitled1.ipynb
Dropbox                        VirtualBox VMs
Google Drive                   anaconda3
IdeaProjects                   mcuxpresso
Library                        my_first_django_project
Movies                         one_array.npy
Music                          temp.pkl
NumpyArrayInputAndOutput.ipynb two_array.npz
Pictures                       untitled
Public                         untitled1
PycharmProjects                x.pkl


In [32]:
c = np.load("two_array.npz")

In [33]:
c["a"]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
c["b"]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# https://docs.scipy.org/doc/numpy-1.15.1/index.html