In [1]:
# Create Array
import numpy as np

In [3]:
np.random.randn(10)

array([ 1.52824473, -0.46384837,  0.64022125, -0.26979297,  0.27407493,
       -1.36813701,  0.89733735,  0.2693957 , -1.45454133, -0.07092052])

In [8]:
a1 = np.random.randint(10, size = (2,3))
print(a1)
a2 = np.random.randint(10, size = 20)
print(a2)
a2 = np.random.randint(10, size = 20).reshape(4, 5)
print(a2)

[[5 8 3]
 [9 3 1]]
[7 4 4 0 3 4 0 9 3 1 6 2 5 7 8 5 9 3 4 3]
[[8 3 9 6 4]
 [1 0 4 6 1]
 [2 8 0 3 5]
 [4 3 6 0 2]]


In [29]:
a = np.random.randint(10, size = 20).reshape(4, 5)
b = np.random.randint(10, size = 20).reshape(4, 5)
a

array([[0, 4, 9, 5, 5],
       [3, 1, 9, 0, 1],
       [3, 7, 3, 4, 9],
       [4, 1, 1, 8, 0]])

In [30]:
b

array([[6, 9, 7, 6, 4],
       [7, 3, 1, 5, 7],
       [2, 9, 7, 9, 3],
       [4, 4, 7, 2, 8]])

In [31]:
a + b

array([[ 6, 13, 16, 11,  9],
       [10,  4, 10,  5,  8],
       [ 5, 16, 10, 13, 12],
       [ 8,  5,  8, 10,  8]])

In [32]:
a * b

array([[ 0, 36, 63, 30, 20],
       [21,  3,  9,  0,  7],
       [ 6, 63, 21, 36, 27],
       [16,  4,  7, 16,  0]])

In [33]:
a / b
# divide 0 error.

array([[0.        , 0.44444444, 1.28571429, 0.83333333, 1.25      ],
       [0.42857143, 0.33333333, 9.        , 0.        , 0.14285714],
       [1.5       , 0.77777778, 0.42857143, 0.44444444, 3.        ],
       [1.        , 0.25      , 0.14285714, 4.        , 0.        ]])

In [34]:
np.mat([[1,2,3], [4,5,6]])
# create a matrix from array

matrix([[1, 2, 3],
        [4, 5, 6]])

In [35]:
np.mat(a)

matrix([[0, 4, 9, 5, 5],
        [3, 1, 9, 0, 1],
        [3, 7, 3, 4, 9],
        [4, 1, 1, 8, 0]])

In [38]:
# Calculation in matrix
A = np.mat(a)
print(A)

[[0 4 9 5 5]
 [3 1 9 0 1]
 [3 7 3 4 9]
 [4 1 1 8 0]]


In [39]:
B = np.mat(b)
print(B)

[[6 9 7 6 4]
 [7 3 1 5 7]
 [2 9 7 9 3]
 [4 4 7 2 8]]


In [40]:
A + B

matrix([[ 6, 13, 16, 11,  9],
        [10,  4, 10,  5,  8],
        [ 5, 16, 10, 13, 12],
        [ 8,  5,  8, 10,  8]])

In [41]:
A - B

matrix([[-6, -5,  2, -1,  1],
        [-4, -2,  8, -5, -6],
        [ 1, -2, -4, -5,  6],
        [ 0, -3, -6,  6, -8]])

In [42]:
A * B
# Invalid. Different from array calculation.

ValueError: shapes (4,5) and (4,5) not aligned: 5 (dim 1) != 4 (dim 0)

In [45]:
b = np.random.randint(10, size = 20).reshape(5, 4)
B = np.mat(b)
A * B
# Valid, M(4 * 5) * M(5 * 4)

matrix([[115, 138,  91,  77],
        [ 94, 115,  58,  30],
        [124, 131, 160, 100],
        [ 59,  88,  41,  87]])

In [47]:
print(a)
sum(a)

[[0 4 9 5 5]
 [3 1 9 0 1]
 [3 7 3 4 9]
 [4 1 1 8 0]]


array([10, 13, 22, 17, 15])

In [48]:
sum(a[0])

23

In [49]:
sum(a[:,0])

10

In [50]:
a.max()

9

In [51]:
max(a[:,0])

4